image: python:3.6.5

include:
  - template: SAST.gitlab-ci.yml

variables:
  SAST_GOSEC_LEVEL: 2


stages:
  - test
  - release

Run Tests:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv env
    - source env/bin/activate
    - cd remoteauth
    - pip install -r ../requirements.txt
    - python manage.py test remote_auth

Release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
  script:
    - echo "Releasing ${CI_COMMIT_TAG}"