image: python:3.6.5

stages:
  - test

Run Tests:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - cd remoteauth
    - python manage.py test remote_auth